INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (1, 'COMIC_BOOKS', 4);
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (2, 'BOOKS', 2);
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (3, 'MOVIES', 5);
INSERT INTO INVENTORY (ID, PRODUCT_CODE, AVAILABLE) VALUES (4, 'MUSIC', 9);